# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d64a66747c004b0c4c387b15989c4013f038712697ac0ccd092c68440c066d3276ab85a9e2778a81b631e5dbd693704d710d4f827989892cdd19c8e66227f9a8

test:
  secret_key_base: 6da9ee08dffdb5b23055ccf20f475625b4f54fa8d45b07e6dcc94bbf51e9919cbb2cb5471c9a7afdcd152179fde5b8fe01f71cd0706e5316751107070e536ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
